### PR TITLE
Various changes, btc price, current time etc.

### PR DESCRIPTION
**Pull request by lonerookie**
Features: 
Current bitcoin price in USD/DKK
Current balance in USD/DKK
Bootup "slogan" (selects randomly from built-in messages)
Show day-of-week and time of last refresh. 

Moved wifi-signal-strength etc from the main-screen to a boot-up screen (as that info is no very relevant for the child looking at the screen IMO). More languages/currencies can fairly easy be included in the code. 
The source-code changes are in a fairly good condition IMO. Biggest thing is that some of the positions of the elements has been hardcoded (and are not relative). So if it should support other screen dimensions than the 2.13 (the one I have), someone with access to the other displays should make the label-positions relative.

### CODE REVIEW

**Comment by lonerookie** [comment]
Note:  Due to problems (infinite reboot) on my 2.31 Lilly TTGO I have disabled 
read_internal_hall_sensor()
and some lines in the hibernate() function. I did not use a lot of time to find out if those lines could still be included or not. But the device seems to work just fine without.

**Comment by ThomasFarstrike** [comment]
Awesome, thanks for the pull request!

> Note: Due to problems (infinite reboot) on my 2.31 Lilly TTGO I have disabled read_internal_hall_sensor() and some lines in the hibernate() function. I did not use a lot of time to find out if those lines could still be included or not. But the device seems to work just fine without.

Interesting... and did that fix the infinite reboot issue? I haven't had that issue myself. Would you mind sharing the diff, especially the hibernate changes, for future reference? It might be useful if we run into the same issue...

**Comment by lonerookie** [comment]
Hi Thomas,
You're welcome - I hope you can use some of it - would be good for me to come back on the main repo :-)

Regarding the "infinte reboot issue" on my device, I did not investigate it very much. The fix is in this commit "Removed deep sleep options that made the device reboot infinitely" https://github.com/LightningPiggy/lightning-piggy/pull/6/commits/d815fe17bbe7ec1c3e5d39b74c28e1425dd0ab68)

I don't think you should merge that part if you have not heard of other users with that issue.

**Comment by ThomasFarstrike** [comment]
> Regarding the "infinte reboot issue" on my device, I did not investigate it very much. The fix is in this commit "Removed deep sleep options that made the device reboot infinitely" [d815fe1](https://github.com/LightningPiggy/lightning-piggy/commit/d815fe17bbe7ec1c3e5d39b74c28e1425dd0ab68))

Interesting, those fixes would make the piggy consume more power in deep sleep but I have no idea of the order of magnitude.
So is this really reproducible - so if you add these lines back in you get infinite reboots and if you remove them, they're gone?
Or is it more "fuzzy"?

If it's very reproducible then you could add them back in one-by-one to figure out which one is causing the issue...

Anyway, thanks for the feedback on this issue!

**Comment by lonerookie** [comment]
> > Regarding the "infinte reboot issue" on my device, I did not investigate it very much. The fix is in this commit "Removed deep sleep options that made the device reboot infinitely" [d815fe1](https://github.com/LightningPiggy/lightning-piggy/commit/d815fe17bbe7ec1c3e5d39b74c28e1425dd0ab68))
> 
> Interesting, those fixes would make the piggy consume more power in deep sleep but I have no idea of the order of magnitude. So is this really reproducible - so if you add these lines back in you get infinite reboots and if you remove them, they're gone? Or is it more "fuzzy"?
> 
> If it's very reproducible then you could add them back in one-by-one to figure out which one is causing the issue...
> 
> Anyway, thanks for the feedback on this issue!

I think you should skip merging this commit. 

I have lost the esp32 where I experienced the problem. I have not seen the problem on any of my other devices using the "official" lightning-piggy code.

I don't think the changes in the "[Removed deep sleep options that made the device reboot infinitely]" commit are neccessary or a benefit to regular users.

**Comment by ThomasFarstrike** [comment]
I've merged all of this in [merged_pull_request_6_by_lonerookie](https://github.com/LightningPiggy/lightning-piggy/tree/merged_pull_request_6_by_lonerookie).

It's pretty much functionally identical, you just need to update config.h with the right values.

Also, lots of small improvements, including the official LightningPiggy logo :-)

**Pull request merged**
